pipelines:
  - name: pipeline_center_tests
    configuration:
      environmentVariables:
        readOnly:
          LHCI_BUILD_CONTEXT__EXTERNAL_BUILD_URL: "$BUILD_URL"
          LHCI_GITHUB_APP_TOKEN: 'gKZOay4Rf:7173980:FMFU7OMZS3H7UEh'
          export LHCI_BUILD_CONTEXT__CURRENT_BRANCH: "$GIT_BRANCH"
    steps:
      - name: exec_lhci
        type: Bash
        configuration:
          inputResources:
            - name: my-app
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
            - add_run_variables current_runid=$run_id
            - echo Previous run ID is $prev_runid
            - echo Current run ID is $current_runid
            - echo $res_myAppRepo_resourcePath
            - echo $res_myAppRepo_gitProvider_name
            - echo $res_myAppRepo_commitSha
