pipelines:
  - name: pipeline_center_tests
    steps:
      - name: exec_lhci
        type: Bash
        configuration:
          environmentVariables:
              LHCI_BUILD_CONTEXT__EXTERNAL_BUILD_URL: "$step_url"
              LHCI_BUILD_CONTEXT__CURRENT_BRANCH: "$res_my_app_branchName"
          integrations:
            - name: lhci_params
          inputResources:
            - name: my_app
          runtime:
            type: image
            image:
              custom:
                name: hemanthsridhar-docker-lhci-server-center.bintray.io/lhci
                tag: "2.0"
                autoPull: true        # default true; pulls image before runx
        execution:
          onStart:
            - echo "Executing LHCI in container"
          onExecute:
            - export LHCI_GITHUB_APP_TOKEN=$int_lhci_params_LHCI_GITHUB_APP_TOKEN
            - cd $res_my_app_resourcePath
            - npm install
            - npm run build
            - echo Previous run ID is $prev_runid
            - lhci autorun --upload.target="temporary-public-storage"
