pipelines:
  - name: pipeline_center_tests
    configuration:
      environmentVariables:
        readOnly:
          LHCI_BUILD_CONTEXT__EXTERNAL_BUILD_URL: "$BUILD_URL"
          LHCI_GITHUB_APP_TOKEN: 'gKZOay4Rf:7173980:FMFU7OMZS3H7UEh'
          export LHCI_BUILD_CONTEXT__CURRENT_BRANCH: "$GIT_BRANCH"
    steps:
      - name: exec_lhci
        type: Bash
        configuration:
          inputResources:
            - name: my_app
          runtime:
            type: image
            image:
              custom:
                name: hemanthsridhar-docker-lhci-server-center.bintray.io/lhci
                tag: 2.0
                autoPull: true        # default true; pulls image before runx
        execution:
          onStart:
            - echo "Executing LHCI in container"
          onExecute:
            - cd $res_my_app_resourcePath
            - npm install
            - npm run build
            - echo Previous run ID is $prev_runid
            - lhci autorun --upload.target="temporary-public-storage"
