pipelines:
  - name: pipeline_center_tests
    steps:
      - name: exec_lhci
        type: Bash
        configuration:
          environmentVariables:
              LHCI_BUILD_CONTEXT__EXTERNAL_BUILD_URL: "$step_url"
              LHCI_BUILD_CONTEXT__CURRENT_BRANCH: "$res_conan_lhci_branchName"
          integrations:
            - name: lhci_params
          inputResources:
            - name: conan_lhci
          runtime:
            type: image
            image:
              custom:
                name: hemanthsridhar-docker-lhci-server-center.bintray.io/lhci
                tag: "3.0"
                autoPull: true        # default true; pulls image before runx
        execution:
          onStart:
            - echo "Executing LHCI in container"
          onExecute:
            - cd $res_conan_lhci_resourcePath/web/ui-server
            - npm install
            - yarn start > server.log 2>&1 &
            - export LHCI_GITHUB_APP_TOKEN=$int_lhci_params_LHCI_GITHUB_APP_TOKEN
            - cd $res_conan_lhci_resourcePath/web/web-source
            - npm install
            - lhci autorun
          onComplete:
            - add_run_files .lighthouseci lhci_report
